#!/usr/bin/env bash
# ============================================================
# debuga.ai — Fix DATABASE_URL Encoding
#
# Problema: docker-compose.yml constrói DATABASE_URL inline:
#   postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
#
# Se POSTGRES_PASSWORD contém caracteres especiais (@, #, %, !, etc.),
# a URL fica malformada e o Node.js pg driver não consegue conectar.
#
# Solução: Este script gera a DATABASE_URL com a senha URL-encoded
# e a adiciona ao .env para que o docker-compose use a versão correta.
#
# Uso:
#   bash scripts/fix-database-url.sh --env /opt/debuga-ai/.env
# ============================================================
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

ENV_FILE=".env"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --env) ENV_FILE="$2"; shift 2 ;;
    *) shift ;;
  esac
done

if [[ ! -f "$ENV_FILE" ]]; then
  echo -e "${RED}✗ .env não encontrado: $ENV_FILE${NC}"
  exit 1
fi

# Load env
set -a
source "$ENV_FILE"
set +a

POSTGRES_USER="${POSTGRES_USER:-debuga}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set}"
POSTGRES_DB="${POSTGRES_DB:-debuga_prod}"

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  debuga.ai — Fix DATABASE_URL Encoding                   ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# Check if password has special characters
SPECIAL_CHARS='@#$%^&*()!+={[}]|:;"<>,?/~`'
HAS_SPECIAL=false
for (( i=0; i<${#POSTGRES_PASSWORD}; i++ )); do
  char="${POSTGRES_PASSWORD:$i:1}"
  if [[ "$SPECIAL_CHARS" == *"$char"* ]]; then
    HAS_SPECIAL=true
    break
  fi
done

if $HAS_SPECIAL; then
  echo -e "${YELLOW}⚠ POSTGRES_PASSWORD contém caracteres especiais!${NC}"
  echo "  Isso pode quebrar a DATABASE_URL no docker-compose.yml."
  echo ""
else
  echo -e "${GREEN}✓ POSTGRES_PASSWORD não contém caracteres especiais.${NC}"
  echo "  A DATABASE_URL do docker-compose.yml deve funcionar normalmente."
  echo ""
fi

# URL-encode the password
ENCODED_PASSWORD=$(python3 -c "import urllib.parse; print(urllib.parse.quote('${POSTGRES_PASSWORD//\'/\\\'}', safe=''))")

# Build the correct DATABASE_URL
CORRECT_URL="postgresql://${POSTGRES_USER}:${ENCODED_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"

echo "  DATABASE_URL gerada:"
echo "    postgresql://${POSTGRES_USER}:***@postgres:5432/${POSTGRES_DB}?sslmode=disable"
echo ""

# Check if DATABASE_URL already exists in .env
if grep -q "^DATABASE_URL=" "$ENV_FILE"; then
  echo "→ Atualizando DATABASE_URL existente no .env..."
  # Use sed to replace the line
  sed -i "s|^DATABASE_URL=.*|DATABASE_URL=${CORRECT_URL}|" "$ENV_FILE"
else
  echo "→ Adicionando DATABASE_URL ao .env..."
  echo "" >> "$ENV_FILE"
  echo "# Generated by fix-database-url.sh (password URL-encoded)" >> "$ENV_FILE"
  echo "DATABASE_URL=${CORRECT_URL}" >> "$ENV_FILE"
fi

echo -e "${GREEN}✓ DATABASE_URL atualizada no .env${NC}"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Próximos passos:"
echo "    1. Verifique: grep DATABASE_URL $ENV_FILE"
echo "    2. Reinicie:  docker compose -f docker/docker-compose.yml restart app"
echo "    3. Valide:    bash scripts/validate-auth.sh"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo -e "${YELLOW}IMPORTANTE: Se você definir DATABASE_URL no .env,${NC}"
echo -e "${YELLOW}o docker-compose.yml NÃO vai sobrescrever com a versão inline.${NC}"
echo -e "${YELLOW}Isso é o comportamento correto — env_file tem prioridade.${NC}"
